name: ps-mg
services:
  app:
    container_name: ps-mg-app
    build: ./app
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: ps-mg-db
    build: ./db
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ps_mg:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  ps_mg: