name: pw_mg
services:
  app:
    container_name: app
    build: ./app
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    build: ./db
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - pw_mg:/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 5
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mxfire1906.com
      PGADMIN_DEFAULT_PASSWORD: mxf
    ports:
      - 5050:80

volumes:
  pw_mg: