name: pwd-mg
services:
  app:
    build: ./app
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  db:
    build: ./db
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - pwd_mg:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin@mxfire1906.com
  #     PGADMIN_DEFAULT_PASSWORD: mxf
  #   ports:
  #     - 5050:80

volumes:
  pwd_mg: